# Generated by Django 5.1.1 on 2024-10-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FD', 'Food'), ('EL', 'Electronics'), ('CL', 'Clothing'), ('FN', 'Furniture'), ('HM', 'Home'), ('VH', 'Vehicle'), ('HA', 'HomeAccesories')], default='FD', max_length=2),
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_buyer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_seller',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
